### ISSUE TITLE
dock-cli docker:install fails with gnu-sed installed

### ISSUE THREAD

**Issue by alistairstead** [inviqa/dock-cli#44]
This is caused by the differing parameter order between sed implementations. I normally install gnu-sed so that it matches other implementations.

``` shell
RUN sed -i '' 's/docker/zzz-dinghy/' /usr/local/Cellar/dinghy/3.0.1/cli/dinghy/dnsmasq.rb
ERR sed: can't read s/docker/zzz-dinghy/: No such file or directory



  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "sed -i '' 's/docker/zzz-dinghy/' /usr/local/Cellar/dinghy/3.0.1/cli/dinghy/dnsmasq.rb" failed.
  Exit Code: 2(Misuse of shell builtins)
  Output:
  ================
  Error Output:
  ================
  sed: can't read s/docker/zzz-dinghy/: No such file or directory

```

Uninstalling gnu-sed resolves the issue however a system check to evaluate the version of `sed` installed and construct the command accordingly may avoid recurring issues with new users.

**Comment by sroze** [comment]
So we have 2 options:
1. Based on the experiment I made, we can check if the result of `sed --version` contains "GNU sed". Important, the `sed --version` command with OSX is failing so we need to silent the error and conclude that the version used in the OSX one.
2. As this `sed` command is only used to [fix the code source of dinghy to change the name of the DNS masq](https://github.com/inviqa/dock-cli/blob/e17c1742d2ede05ccaed233b5fe91229cbd1ca97/src/Installer/Docker/Dinghy.php#L69) they are using, we may use another solution than this one or better, contribute a `--no-dns` option to dinghy.
