### ISSUE TITLE
Be able to run dock-cli anywhere in a Git project

### ISSUE THREAD

**Issue by sroze** [inviqa/dock-cli#46]
If we're in a project but not at its root, we can't run project-related commands. As the `git` cli is doing, we should be able to do so.

**Comment by tasuki** [comment]
As a matter of fact, we can.

The following commands work from any subdirectory of a project:
`help`, `list`, `logs`, `ps`, `run`, `self-update`, `start`, `stop`, `docker:install`, `docker:restart`

[Edit: At least under Debian]

**Comment by sroze** [comment]
@tasuk oh, you're right, even under OSX ! Thanks `docker-compose` :+1:
