### ISSUE TITLE
docker-compose up -d times out after 60s

### ISSUE THREAD

**Issue by tonypiper** [inviqa/dock-cli#49]
currently `docker-compose up -d` times out after 60 seconds when running `dock-cli start`. When a container has already been built this is probably acceptable as it might indicate some other problem, but when a container is new it'll take longer than that.

**Comment by tonypiper** [comment]
workaround is to run `docker-compose up -d` manually.

**Comment by sroze** [comment]
@tonypiper you may want to review #50
