### ISSUE TITLE
docker communication fails from host due to bad ssl auth

### ISSUE THREAD

**Issue by jon-acker** [inviqa/dock-cli#54]
For example running "docker ps" on the host machine complains that:

``` sh
An error occurred trying to connect: Get https://127.0.0.1:2376/v1.19/containers/json: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:277145398527496638593538438487973883033")
```

Nevertheless ssh'ing into the vm and running docker commands from there works fine.

**Comment by sroze** [comment]
@jon-acker could you try to upgrade Dinghy and try again ?

```
dinghy upgrade
```

**Comment by sroze** [comment]
After further investigations, that come from the fact that another VM has previously bind the port 2376 and then Dinghy's VM bind another one to the host. If there's another case, then we can introduce a test in the doctor.
