### ISSUE TITLE
Differences with Docker compose?

### ISSUE THREAD

**Issue by mnapoli** [inviqa/dock-cli#71]
Hi there, interesting project! What are the differences with docker compose? Also it might be interesting to document this in the readme too.

**Comment by sroze** [comment]
Hi ! This tool is using docker-compose and its goal is to add an abstraction layer on top of that, especially for local Docker development environment installation, and common useful features such as the `ps` command that prints the DNS resolution of containers.

It'll also be the home of small project-related extensions, to ease developer's life when dealing with Docker-based projects :+1:

**Comment by mnapoli** [comment]
:+1: thanks for the info ;)
