### ISSUE TITLE
Run `docker:doctor` when running `start`

### ISSUE THREAD

**Issue by sroze** [inviqa/dock-cli#73]
I think that's a good idea to run silently the `docker:doctor` command before each `start` commands.

If something fails, then display a warning message and the failed test, and then propose to fix the problem by running the corresponding solution registered in the doctor.

**Comment by mareg** [comment]
:+1:

**Comment by tasuki** [comment]
:+1: it's fast enough.

**Comment by sroze** [comment]
PR here: #77 :smiley:

**Comment by sroze** [comment]
Closed by #77 :)
