### ISSUE TITLE
Display the URL of components while starting up docker

### ISSUE THREAD

**Issue by sroze** [inviqa/dock-cli#8]
When using `dock-cli up`, we should display the DNS addresses of started components.

The idea is that, after `up`, a table such as this one would be displayed:

```
+-----------+---------------------+------+
| Component | DNS address         | Port |
+-----------+---------------------+------+
| web       | http://[...].docker | 80   |
| mysql     | tcp://[...].docker  | 3306 |
+-----------+---------------------+------+
```

The point is also that we should display logs, so many options:
1. Display the table then follow the logs of containers (which may hide the table quickly, as for instance MySQL logs at startup is ~50 lines)
2. Display the table and finish the command, we need to type `dock-cli logs` (to create) to follow logs.
3. Ask `y`/`n` to go to case 1 or 2.

**Comment by walterdolce** [comment]
I think it would be great to have a separate command to display both the table and the logs.

I see the `dock-cli up` as an environment bootstrap command only. This could include the table displayed right after the environment finishes bootstrapping (chained commands) but not the logs (which is something not related to the bootstrap action itself, but something "external" the bootstrapping mechanism). 

Does that make sense?

**Comment by richardmiller-zz** [comment]
Separate commands sounds good to me. The logs hiding the table when that may have been what you were after sounds like a potential ux issue.

**Comment by tonypiper** [comment]
:+1:
