### ISSUE TITLE
Shell sourcing requirement after installation should be more explicit

### ISSUE THREAD

**Issue by sroze** [inviqa/dock-cli#9]
We need to source the environment variable files (or start a new tab/terminal) after installation to have the new environment variables.

**This have to be more explicit** or done automatically.

**Comment by sroze** [comment]
To feel like it's done automatically for the current shell, we can use that solution (thanks @ciaranmcnulty):

``` php
putenv('FOO=bar');
passthru(getenv('SHELL'));
```

**Comment by richardmiller-zz** [comment]
Would that work? Looks like it would work for the current script being run but would it work for running something else afterwards in the same shell?

**Comment by sroze** [comment]
Well, this technique will work for the next commands (after running `docker:install`) in the same "shell window". Because we are also adding these envs in the `.bash_profile` or `.zshenv` file, they will be loaded for any other new shell.

**Comment by ciaranmcnulty** [comment]
`pcntl_exec` is better than `passthru`, but this will spawn a new shell which has the environment set up. If you're also setting it up in the `.bash_profile` this avoids having to reload these things.

**Comment by sroze** [comment]
So we can just prevent using the `putenv` calls, that's right ! :)
