### ISSUE TITLE
Xcode not installed

### ISSUE THREAD

**Issue by paalsoberg** [inviqa/dock-cli#90]
When Xcode is not installed..

  [Symfony\Component\Process\Exception\ProcessFailedException]  
  The command "brew install caskroom/cask/brew-cask" failed.  
  Exit Code: 1(General error)  
  Output:  
  ================  
  Error Output:  
  ================  
  Agreeing to the Xcode/iOS license requires admin privileges, please re-run  
  as root via sudo.

**Comment by sroze** [comment]
By running `xcode-select --install`
