### ISSUE TITLE
Various installation issues

### ISSUE THREAD

**Issue by Elfiggo** [inviqa/dock-cli#96]
On a clean El Capitan install there are too many dependencies in brew required to get to the point where you should be able to run docker.

Would be useful to have a FAQ section to mention things like brew ask and running brew doctor etc... to help fix issues

**Comment by sroze** [comment]
Thanks for reporting @Elfiggo.

What are the issues you are facing with El Capitan? If solved, what did you do to solve them?

**Comment by Elfiggo** [comment]
Mainly brew and brew cask needed to be installed and linked, various rounds of brew doctor and fixing those issues.

Mixed installation instructions during the beta phase.

System requirements would be good as part of the install instructions

**Comment by sroze** [comment]
> The answer to the docker problem is a simple one. `docker:doctor` fixes everything.
> -- @Elfiggo 

Closing.
